language: node_js
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions
# latest lts & latest
node_js:
  - lts/*
  - node
script: CI=travis npm run install-deps && npm run test-cover-report
notifications:
  email: false
