coverage:
  status:
    promise.ify:
      flags: pify
    promise.map:
      flags: pmap
    promise.obj:
      flags: pobj
    promise.retry:
      flags: pretry
    promise.timeout:
      flags: ptimeout

flags:
  pify:
    paths:
      - promise.ify/
  pmap:
    paths:
      - promise.map/
  pobj:
    paths:
      - promise.obj/
  pretry:
    paths:
      - promise.retry/
  ptimeout:
    paths:
      - promise.timeout/
